[project]
name = "acapy-did-indy"
version = "0.1.0"
description = "ACA-Py DID Indy support prototype"
authors = [
    {name = "Daniel Bluhm", email = "dbluhm@pm.me"},
]
dependencies = [
    "did-indy-py[client,demo,driver] @ git+https://github.com/Indicio-tech/did-indy-py.git@feat/updated-models",
    "pytest>=8.4.0"
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "Apache-2.0"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "fastapi[standard]>=0.112.2",
    "ruff>=0.6.3",
    "pytest>=8.3.3",
]
[tool.pdm.group.did_web_server.dependencies]
fastapi = ">=0.112.2"
[tool.pdm.group.acapy.dependencies]
acapy-agent = ">=1.2.2"
[tool.pdm.group.demo.dependencies]
acapy-controller = ">=0.3.0"

