FROM python:3.12-slim-bookworm as base
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y curl && apt-get clean
ENV PDM_VERSION=2.24.0
ENV PDM_HOME=/opt/pdm
RUN curl -sSL https://pdm-project.org/install-pdm.py | python3 -


FROM python:3.12-slim-bookworm
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y curl git && apt-get clean

COPY --from=base /opt/pdm /opt/pdm

ENV PATH="/opt/pdm/bin:$PATH"

# Setup project
COPY pyproject.toml pdm.lock README.md demo_driver/driver.py demo_driver/healthcheck.py ./
COPY demo_driver/demo.ledgers.toml /run/secrets/ledgers.toml
RUN pdm install -G :all

ENTRYPOINT ["pdm", "run"]
CMD ["fastapi", "dev", "driver.py", "--host", "0.0.0.0", "--port", "80"]
